import { NextResponse } from "next/server";
import { serverDb } from "@/lib/serverDb";
import crypto from "crypto";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { action, targetId, emailOrPhone, roleUpdates, otpLength = 6 } = body;

    if (action === "get-users") {
      const users = serverDb.getUsers().map(u => ({
        id: u.id,
        name: u.name,
        emailOrPhone: u.emailOrPhone,
        isAdmin: u.isAdmin,
        isCreator: u.isCreator,
        failedLogins: u.failedLogins,
        lockedUntil: u.lockedUntil
      }));
      return NextResponse.json({ success: true, users });
    }

    if (action === "update-role") {
      if (!targetId || !roleUpdates) {
        return NextResponse.json({ success: false, error: "targetId and roleUpdates are required." }, { status: 400 });
      }
      const user = serverDb.getUserById(targetId);
      if (!user) {
        return NextResponse.json({ success: false, error: "User not found." }, { status: 404 });
      }
      
      serverDb.updateUser(targetId, roleUpdates);
      serverDb.addAuditLog(
        "ADMIN_USER_UPDATE",
        "127.0.0.1",
        "Admin Console",
        `Admin updated roles for user ${user.emailOrPhone}: ${JSON.stringify(roleUpdates)}`
      );
      return NextResponse.json({ success: true });
    }

    if (action === "generate-otp") {
      if (!emailOrPhone) {
        return NextResponse.json({ success: false, error: "emailOrPhone is required." }, { status: 400 });
      }
      
      // Initialize global otpStore if it doesn't exist
      if (!(global as any).otpStore) {
        (global as any).otpStore = new Map<string, string>();
      }
      
      // Generate secure numeric OTP code
      const digits = "0123456789";
      let code = "";
      for (let i = 0; i < otpLength; i++) {
        code += digits[crypto.randomInt(0, 10)];
      }

      (global as any).otpStore.set(emailOrPhone.trim().toLowerCase(), code);
      
      serverDb.addAuditLog(
        "ADMIN_OTP_GENERATED",
        "127.0.0.1",
        "Admin Console",
        `Emergency OTP generated by administrator for identifier: ${emailOrPhone}`
      );

      return NextResponse.json({ success: true, code });
    }

    return NextResponse.json({ success: false, error: `Invalid action: ${action}` }, { status: 400 });
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    return NextResponse.json(
      { success: false, error: `Action failed: ${errorMsg}` },
      { status: 500 }
    );
  }
}
