import { NextResponse } from "next/server";
import { serverDb } from "@/lib/serverDb";
import crypto from "crypto";
import { sanitizeInput } from "@/lib/security";

export async function POST(request: Request) {
  try {
    const cookies = request.headers.get("cookie") || "";
    const getCookie = (name: string) => {
      const match = cookies.match(new RegExp("(^| )" + name + "=([^;]+)"));
      return match ? match[2] : null;
    };
    
    const accessToken = getCookie("session_at");
    if (!accessToken) {
      return NextResponse.json({ success: false, error: "Unauthorized access." }, { status: 401 });
    }

    const { createClient } = await import("@supabase/supabase-js");
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://dummy-project.supabase.co";
    const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "dummy-anon-key";
    const supabase = createClient(supabaseUrl, supabaseAnonKey);

    const { data: { user }, error: authError } = await supabase.auth.getUser(accessToken);
    if (authError || !user) {
      return NextResponse.json({ success: false, error: "Unauthorized access." }, { status: 401 });
    }

    // Verify admin role in database profiles table
    const { data: profile } = await supabase
      .from("profiles")
      .select("role")
      .eq("id", user.id)
      .single();

    const role = profile?.role || "user";
    if (role !== "admin" && user.email !== "theoldverse@gmail.com") {
      return NextResponse.json({ success: false, error: "Access Denied: Administrative role required." }, { status: 403 });
    }

    const rawBody = await request.json();
    const body = sanitizeInput(rawBody);
    const { action, targetId, emailOrPhone, roleUpdates, otpLength = 6 } = body;

    if (action === "get-users") {
      const allUsers = await serverDb.getUsers();
      const users = allUsers.map(u => ({
        id: u.id,
        name: u.name,
        emailOrPhone: u.emailOrPhone,
        isAdmin: u.isAdmin,
        isCreator: u.isCreator,
        failedLogins: u.failedLogins,
        lockedUntil: u.lockedUntil
      }));
      return NextResponse.json({ success: true, users });
    }

    if (action === "update-role") {
      if (!targetId || !roleUpdates) {
        return NextResponse.json({ success: false, error: "targetId and roleUpdates are required." }, { status: 400 });
      }
      const user = await serverDb.getUserById(targetId);
      if (!user) {
        return NextResponse.json({ success: false, error: "User not found." }, { status: 404 });
      }
      
      await serverDb.updateUser(targetId, roleUpdates);
      await serverDb.addAuditLog(
        "ADMIN_USER_UPDATE",
        "127.0.0.1",
        "Admin Console",
        `Admin updated roles for user ${user.emailOrPhone}: ${JSON.stringify(roleUpdates)}`
      );
      return NextResponse.json({ success: true });
    }

    if (action === "generate-otp") {
      if (!emailOrPhone) {
        return NextResponse.json({ success: false, error: "emailOrPhone is required." }, { status: 400 });
      }
      
      // Initialize global otpStore if it doesn't exist
      if (!(global as any).otpStore) {
        (global as any).otpStore = new Map<string, string>();
      }
      
      // Generate secure numeric OTP code
      const digits = "0123456789";
      let code = "";
      for (let i = 0; i < otpLength; i++) {
        code += digits[crypto.randomInt(0, 10)];
      }

      (global as any).otpStore.set(emailOrPhone.trim().toLowerCase(), code);
      
      await serverDb.addAuditLog(
        "ADMIN_OTP_GENERATED",
        "127.0.0.1",
        "Admin Console",
        `Emergency OTP generated by administrator for identifier: ${emailOrPhone}`
      );

      return NextResponse.json({ success: true, code });
    }

    return NextResponse.json({ success: false, error: `Invalid action: ${action}` }, { status: 400 });
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    return NextResponse.json(
      { success: false, error: `Action failed: ${errorMsg}` },
      { status: 500 }
    );
  }
}
